name: Continuous Integration

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Lint
        run: |
          find scripts/ | grep -e '.sh$' | xargs shellcheck

      - name: Run services
        run: docker compose up --wait

      - name: Run tests
        run: |
          ./scripts/ecr-credential.sh

      - name: Print logs
        if: ${{ always() }}
        run: docker compose logs
